//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportMidFile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyTravelsEntities : DbContext
    {
        public EasyTravelsEntities()
            : base("name=EasyTravelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inq> Inqs { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<TransportReg> TransportRegs { get; set; }
        public virtual DbSet<Vehiclelist> Vehiclelists { get; set; }
    }
}
