//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportMidFile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportReg
    {
        public int TranportId { get; set; }
        public string CompanyName { get; set; }
        public string EmailID { get; set; }
        public string Phone { get; set; }
        public string Type { get; set; }
        public string Password { get; set; }
        public bool EmailVarification { get; set; }
        public System.Guid ActivationCode { get; set; }
    }
}
