//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportMidFile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiclelist
    {
        public int id { get; set; }
        public int VehicleID { get; set; }
        public string VehicleName { get; set; }
        public string Type { get; set; }
        public string StartingPoint { get; set; }
        public string FinishingPoint { get; set; }
        public string TotalSeat { get; set; }
        public string Price { get; set; }
        public string Offer { get; set; }
        public string ExtraInfo { get; set; }
    }
}
